# Site settings
title:  Raf Bristol PT
email:
description: > # this means to ignore newlines until "baseurl:"
  Personal training services by Raf Bristol
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rafbristolpt.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
